# Математика для машинного обучения
## Домашнее задание №4

_Автор задания: Илья Щуров_

Подготовлено для программы «[Практический анализ данных и машинное обучение](https://cs.hse.ru/dpo/bigml)» (ФКН НИУ ВШЭ).

Задание выполнила: *Хужина Вария*

### О задании

В задании встречаются задачи трёх видов. Обычные задачи — чаще всего, простые задачи на определения. Их нужно сделать, если понятия, обсуждавшиеся на лекции, кажутся вам новыми или прочно забытыми. Задачи со звёздочкой — на доказательства. Их можно пропустить, если вы проходите этот материал впервые, но они помогут разобраться в нём глубже. Они также не являются сложными при наличии некоторой математической подготовки. Наконец, задачи с двумя звёздочками — для тех, кто имеет математическое образование.

Вы можете выбрать, какой тип задач вы хотите решать — скорее всего, если вы можете решить задачи со звёздочкой, то задачи без звёздочек будут для вас слишком простыми (но может быть и нет — в любом случае, просмотрите их и поймите, являются ли они для вас совсем устными; если нет — лучше сделайте их).

### Задача 1
Рассмотрим уравнение
$$2x_1 + 3x_2 - 5x_3 = 0.$$

Оно задаёт некоторую плоскость. Найти координаты двух линейно независимых векторов, лежащих в этой плоскости.

**Подсказка.** Искомые векторы можно найти в виде $(x_1^1, 1, 0)$ и $(x_1^2, 0, 1)$ (верхний индекс — это номер вектора, а не степень). Докажите, что любые такие векторы линейно независимы (какими бы ни были $x_1^1$ и $x_1^2$). Найдите $x_1^1$ и $x_1^2$ из уравнения.

**Решение**    
Пусть искомые векторы $v_1$ и $v_2$ имеют координаты $(x_1^1, 1, 0)$ и $(x_1^1, 0, 1)$ соответсвенно. Тогда:   
для $v_1$ можно записать:    
$2x_1^1 + 3 = 0$, отсюда $x_1 = \frac{-3}{2}$    
для  $v_2$ можно записать:    
$2x_1^2 + 5 = 0$, отсюда $x_1 = \frac{-5}{2}$     
Докажем, что любые векторы $v_1$ и $v_2$ заданного вида линейно независимы. Иначе можно сказать, что компоненты векторов не пропорциональны. Учитывая, что один из компонент вектора $v_1$ равен нулю,  то для вектора $v_2$ соответсвующий компонент должен  быть тоже равен нулю в случае их зависимости, так как это не выполняется $1 \neq 0$, то векторы линейно независимы.

### Задача 2

Рассмотрим систему уравнений

$$\begin{cases}
x_1 - 2x_2 + x_3 = 0 \\
2x_1 + 3x_2 - 5x_3 = 0
\end{cases}$$

Показать, что система задаёт некоторую прямую и задать её в параметрическом виде.

**Подсказка.** Выразить $x_1$ и $x_2$ через $x_3$, затем найти вектор вида $(x_1, x_2, 1)$, лежащий на этой прямой.

**Решение**   
Из первого уравнения:    
$x_3 = 2x_2 - x_1$    
Подставим во второе:    
$2x_1 + 3x_2 - 10x_2 + 5x_1 = 0$    
$7x_1 - 7x_2 = 0$   
$x_1 - x_2 = 0$   
$x_1 = x_2$    
Найдем вектор вида $(x_1, x_2, 1)$       
$(1, 1, 1)$

### Задача 3
Рассмотрим систему уравнений

$$\begin{cases}
x_1 + 2x_2 + x_3 + x_4 = 0 \\
2x_1 + 3x_2 - 5x_3 - x_4 = 0
\end{cases}$$

Показать, что система задаёт некоторую двумерную плоскость и найти координаты двух линейно незвисимых векторов, лежащих в этой плоскости.


**Подсказка.** Искомые векторы можно найти в виде $(x_1^1, x_2^1, 1, 0)$ и $(x_1^2, x_2^2, 0, 1)$.

**Решение**    
Аналогично предыдущей задаче, выразиим $x_4$ из первого уравнения:    
$x_4 = -x_1 - 2x_2 - x_3 = 0$    
Подставим во второе:    
$2x_1 + 3x_2 - 5x_3 + x_1 + 2x_2 + x_3 = 0$    
$3x_1 + 5x_2 - 4x_3 = 0$   
Найдем координаты двух линейно независимых векторов в виде $(x_1^1, x_2^1, 1, 0)$ и $(x_1^2, x_2^2, 0, 1)$:    
Подставим координаты первого вектора в уравнение для плоскости:
$3x_1^1 + 5x_2^1 - 4 = 0$     
$3x_1^1 + 5x_2^1 = 4$  
И, например, в первое уравнение системы:    
$x_1^1 + 2x_2^1 = -1$    
Отсюда $x_1^1 = -1 - 2x_2^1$,    
$x_2^1 = -7$, $x_1^1 = 13$    
$(x_1^1, x_2^1, 1, 0) = (13, -7, 1, 0)$   
    
Для второго вектора, анологично, получим: 
Подставим координаты в уравнение для плоскости:    
$3x_1 + 5x_2 = 0$ 
И, например, в первое уравнение системы:    
$x_1^1 = -1 - 2x_2^1$    
Отсюда:    
$x_2^1 = -3$, $x_1^1 = 5$        
$(x_1^2, x_2^2, 1, 0) = (5, -3, 0, 1)$

**Определение**

*Линейным подпространством* $V \subset \mathbb R^n$ называется такое подмножество векторов, что для любых $u, v\in V$ и любого скаляра $\lambda \in \mathbb R$:

- $u + v \in V$;
- $\lambda u \in V$.

*Аффинным подпространством* $W \subset \mathbb R^n$  множество векторов $\{u_0 + v \mid v \in  V\}$, получаемых из некоторого фиксированного вектора $u_0$ прибавлением всевозможных векторов из линейного подпространства $V$. Иными словами, аффинное подпространство — это результат сдвига линейного подпространства на некоторый фиксированный вектор.

### Задача 4
Является ли линейным подпространством множество векторов $(x_1, x_2, x_3)\in \mathbb R^3$, заданное следующим образом (каждое условие — отдельный пункт):

1. $x_1=0$;
1. $x_1^2 + x_2 + x_3 = 0$ (здесь $x_1^2$ — это $x_1$ в квадрате);
2. $x_1 + x_2 + x_3 = 1$;
3. $x_1=0$ или $x_2=0$.

**Решение**    
Пусть вектор $v$ имееет координаты $(x_1^v, x_2^v, x_3^v)$, а вектор $u$ координаты $(x_1^u, x_2^u, x_3^u)$, причем $u, v \in V$, где $V$ - подпространство векторов  $(x_1, x_2, x_3)\in \mathbb R^3$        
1. Если $x_1=0$, тогда $V$ - подпространство векторов  $(0, x_2, x_3)\in \mathbb R^3$    
   $v = (0, x_2^v, x_3^v)$, $u = (0, x_2^u, x_3^u)$    
   $u + v = (0, x_2^v + x_2^u, x_3^v + x_3^u) \in V$    
   $\lambda u = (0,\lambda x_2^u, \lambda x_3^u)\in V$    
   Ответ: является линейным
2. Если $x_1^2 + x_2 + x_3 = 0$, тогда        
   ${x_1^v}^2+ x_2^v+ x_3^v = 0$ и ${x_1^u}^2+ x_2^u+ x_3^u = 0$    
   $u + v = x_1^v + x_1^u, x_2^v + x_2^u, x_3^v + x_3^u$    
   ${(x_2^v + x_2^u)}^2 + x_2^v + x_2^u + x_3^v + x_3^u \neq 0$, так как ${(x_2^v + x_2^u)}^2 \neq {x_2^v}^2 + {x_2^u}^2$     
   Ответ: не является линейным
3. Если $x_1 + x_2 + x_3 = 1$, тогда     
   $x_1^v+ x_2^v+ x_3^v = 1$ и $x_1^u+ x_2^u+ x_3^u = 1$    
   $u + v = (x_1^v + x_1^u, x_2^v + x_2^u, x_3^v + x_3^u)$    
   $x_1^v + x_1^u + x_2^v + x_2^u + x_3^v + x_3^u = 2$    
   Ответ: не является линейным
4. $x_1=0$ или $x_2=0$    
   для $x_1=0$ показано, что пространство является линейным в п.1,
   аналогично для $x_2=0$,   
   положим теперь, что $x_1=0$ и $x_2=0$, тогда   
   $v = (0, 0, x_3^v)$, $u = (0, 0, x_3^u)$   
   очевидно, что в и этом случае:
   $u + v \in V$ и $\lambda u \in V$    
   Теперь положим, что     
   $v = (x_1^v, 0, x_3^v)$, $u = (0, x_2^u, x_3^u)$, тогда
   $u + v = (x_1^v, x_2^u, x_3^v + x_3^u)$, у этого вектора ни один из компонет не равен нулю, следовательно пространство не является линейным    
   Ответ: не является линейным    

### Задача 5 (*)
Доказать, что для любой прямоугольной матрицы $A$ множество всех решений системы $Ax=0$ является линейным подпространством (если оно непусто, то есть если хоть какие-то решения у системы есть), а множество всех решений системы $Ax=b$ является аффинным подпространством. Как связаны решения этих двух систем?

**Решение**    
Положим, что система линеный уравнений вида $Ax = 0$ имеет решение $x = (x_1, x_2, ..., x_n) \in V$, $V \in \mathbb R^n$, иначе говоря, решение системы образует подпространсвто решений $V \in \mathbb R^n$, так что $x = (x_1, x_2, ..., x_n) \in \mathbb V$ такое, что $Ax = 0$, положим, теперь, что накоторые векторы $u, v \in V$.     
$v = (x_1^2, x_2^v,\dots, x_n^v)$, $u = (x_1^u, x_2^u,\dots, x_n^u)$   
$Av = 0$ и $Au = 0$    
Проверим, является ли подпространство $V$ линейным:    
1. $u + v = (x_1^u + x_1^v,\ x_2^u + x_2^v,\ \dots,\ x_n^u + x_n^v)$    
$A(u + v) = Au + Av = 0$
2. $\lambda u = (\lambda x_1^u , \lambda x_2^u , \dots, \lambda x_n^u)$   
$A(\lambda u) = A\lambda u = \lambda (Av) = 0$    

Аналогичные рассуждения проведем, для уравнения вида $Ax = b$, пусть теперь пространство решений системы $V_b \in \mathbb R^n$ положим, теперь, что накоторые векторы $u_b, v_b \in V_b$    
$Av_b = b$ и $Au_b = b$    
Проверим, является ли подпространство $V_b$ линейным:    
1. $u_b + v_b = (x_1^{u_b} + x_1^{v_b},\ x_2^{u_b} + x_2^{v_b},\ \dots,\ x_n^{u_b} + x_n^{v_b})$    
$A(u_b + v_b) = Au_b + Av_b = 2b \neq b$
2. $\lambda u_b = (\lambda x_1^{u_b} , \lambda x_2^{u_b} , \dots, \lambda x_n^{u_b})$   
$A(\lambda u_b) = A\lambda u_b = \lambda (Av_b) = \lambda b \neq b$   

Докажем, что пространство $V_b$ аффинное. Пусть $Ax = 0$ задает подпространство $V \in \mathbb R^n$, как было показано выше, оно являтся линейным, и пусть задано подпространство $V_b \in \mathbb R^n$ как решение системы $Ax = b$. Пусть существует некторое решение $x_0 \in V_b$, тогда $Ax_0 = b$, прибавление нуля не изменит это выражение, тогда рассмотрим систему $Ax_0 + Ax = b$ иначе можно записать $A(x_0 + x) = b$. Решения данной системы являеются вектора вида $x_0 + x$, где $x$ принажлежит линейному подпространству $x \in V$, вектор $(x_0 + x) \in V_b$, значит $V_b - аффинное  подпространство.$ 

### Задача 6

Докажите, что $(AB)^T=B^T A^T$ для любых матриц $A$, $B$, таких, что определено произведение $AB$. Здесь $X^T$ — транспонированная матрица $X$.

**Решение**    
Пусть     
$$A_{m \times n} = \begin{pmatrix}
a_{11} & a_{12}& \ldots& a_{1n}\\
a_{21} & a_{22}& \ldots& a_{2n}\\
\ldots & \ldots & \ldots & \ldots\\
a_{m1}& a_{m2}&\ldots &a_{mn}
\end{pmatrix} \ \ 
B_{n \times k} = \begin{pmatrix}
b_{11} & b_{12}& \ldots& b_{1k}\\
b_{21} & b_{22}& \ldots& b_{2k}\\
\ldots & \ldots & \ldots & \ldots \\
b_{n1}& b_{n2}&\ldots &b_{nk}
\end{pmatrix}$$    

$$(A^T)_{n \times m} = \begin{pmatrix}
a_{11} & a_{21}& \ldots& a_{m1}\\
a_{12} & a_{22}& \ldots& a_{m2}\\
\ldots & \ldots & \ldots & \ldots \\
a_{1n}& a_{2n}&\ldots &a_{mn}
\end{pmatrix} \ \ 
(B^T)_{k \times n} = \begin{pmatrix}
b_{11} & b_{21}& \ldots& b_{n1}\\
b_{12} & b_{22}& \ldots& b_{n2}\\
\ldots & \ldots & \ldots & \ldots \\
b_{1k}& b_{2k}&\ldots &b_{kn}
\end{pmatrix}$$ 

Тогда    
$$AB_{m \times k} =  \begin{pmatrix}
a_{11}b_{11} + a_{12}b_{21} + a_{1n}b_{n1}&a_{11}b_{12} + a_{12}b_{22} + a_{1n}b_{n2}&  \ldots & a_{11}b_{1k} + a_{12}b_{2k} + a_{1n}b_{nk}\\
a_{21}b_{11} + a_{22}b_{21} + a_{2n}b_{n1}&a_{21}b_{12} + a_{22}b_{22} + a_{2n}b_{n2}&  \ldots & a_{21}b_{1k} + a_{22}b_{2k} + a_{2n}b_{nk}\\
\ldots & \ldots & \ldots & \ldots \\
a_{m1}b_{11} + a_{m2}b_{21} + a_{mn}b_{n1}&a_{m1}b_{12} + a_{m2}b_{m2} + a_{mn}b_{n2}&  \ldots & a_{m1}b_{1k} + a_{m2}b_{2k} + a_{mn}b_{nk}\\
\end{pmatrix}$$    
$$(AB^T)_{k \times m} =  \begin{pmatrix}
a_{11}b_{11} + a_{12}b_{21} + a_{1n}b_{n1} & a_{21}b_{11} + a_{22}b_{21} + a_{2n}b_{n1} &  \ldots &a_{m1}b_{11} + a_{m2}b_{21} + a_{mn}b_{n1} \\
a_{11}b_{12} + a_{12}b_{22} + a_{1n}b_{n2}&a_{21}b_{12} + a_{22}b_{22} + a_{2n}b_{n2}&  \ldots &a_{m1}b_{12} + a_{m2}b_{m2} + a_{mn}b_{n2} \\
\ldots & \ldots & \ldots & \ldots \\
a_{11}b_{1k} + a_{12}b_{2k} + a_{1n}b_{nk}&a_{21}b_{1k} + a_{22}b_{2k} + a_{2n}b_{nk}&  \ldots & a_{m1}b_{1k} + a_{m2}b_{2k} + a_{mn}b_{nk}\\
\end{pmatrix}$$    
$$ B^TA^T = \begin{pmatrix}
b_{11}a_{11} + b_{21}a_{12} + b_{n1}a_{1n} & b_{11}a_{21} + b_{21}a_{22} + b_{n1}a_{2n} &  \ldots &b_{11}a_{m1} + b_{21}a_{m2} + b_{n1}a_{mn} \\
b_{12}a_{11} + b_{22}a_{12} + b_{n2}a_{1n}&b_{12}a_{21} + b_{22}a_{22} + b_{n2}a_{2n}&  \ldots &b_{12}a_{m1} + b_{m2}a_{m2} + b_{n2}a_{mn} \\
\ldots & \ldots & \ldots & \ldots \\
b_{1k}a_{11} + b_{2k}a_{12} + b_{nk}a_{1n}&b_{1k}a_{21} + b_{2k}a_{22} + b_{nk}a_{2n}&  \ldots & b_{1k}a_{m1} + b_{2k}a_{m2} + b_{nk}a_{mn}\\
\end{pmatrix}$$   
Нетрудно увидитеть, что $AB^T = B^TA^T$

### Задача 7
Рассмотрим *диагональную* матрицу 
$$D=D(\lambda_1, \lambda_2, \ldots, \lambda_n) = 
\begin{pmatrix}
\lambda_1 & 0& \ldots& 0\\
0& \lambda_2& \ldots &0\\
\vdots & \vdots & \ddots & \vdots \\
0& 0&\ldots &\lambda_n
\end{pmatrix}.
$$
(На диагонали — числа $\lambda_1,\lambda_2, \ldots, \lambda_n$, все остальные компоненты нулевые.)

Рассмотрим произвольную матрицу $A$ подходящего размера (такого, чтобы соответствующие произведения были определены).

1. Как связаны матрицы $A$ и $DA$?
2. Как связаны матрицы $A$ и $AD$?

**Решение**    
Пусть   
$A_{n \times n} = \begin{pmatrix}
a_{11} & a_{12}& \ldots& a_{1n}\\
a_{21} & a_{22}& \ldots& a_{2n}\\
\ldots & \ldots & \ldots & \ldots\\
a_{n1}& a_{n2}&\ldots &a_{nn}
\end{pmatrix} \ \
D_{n \times n} = \begin{pmatrix}
\lambda_1 & 0& \ldots& 0\\
0 & \lambda_2& \ldots& 0\\
\vdots & \vdots & \ddots & \vdots\\
0& 0&\ldots &\lambda_n
\end{pmatrix} $

1.    При умножении справа матрицы $A$ на матрицу $D$ $i$-ый столбец матрицы  $A$ умножется на соответсвующий элемент $\lambda_i$:   
$AD = \begin{pmatrix}
\lambda_1a_{11} & \lambda_2a_{12}& \ldots& \lambda_na_{1n}\\
\lambda_1a_{21} & \lambda_2a_{22}& \ldots& \lambda_na_{2n}\\
\ldots & \ldots & \ldots & \ldots\\
\lambda_1a_{n1}& \lambda_2a_{n2}&\ldots &\lambda_na_{nn}
\end{pmatrix}$

1.    При умножении слева матрицы $A$ на матрицу $D$ $i$-ая строка матрицы  $A$ умножется на соответсвующий элемент $\lambda_i$:   
$DA = \begin{pmatrix}
\lambda_1a_{11} & \lambda_1a_{12}& \ldots& \lambda_1a_{1n}\\
\lambda_2a_{21} & \lambda_2a_{22}& \ldots& \lambda_2a_{2n}\\
\ldots & \ldots & \ldots & \ldots\\
\lambda_na_{n1}& \lambda_na_{n2}&\ldots &\lambda_na_{nn}
\end{pmatrix}$

### Задача 8
С помощью `numpy` найти произведение матриц

$$
A = \begin{pmatrix}
1 & 2 & 3 & 4 \\
5 & 6 & 7 & 8
\end{pmatrix}
$$

и 

$$B = \begin{pmatrix}
4 & 2 & 1 \\
3 & 5 & 7 \\
1 & 9 & 2 \\
2 & 4 & 1
\end{pmatrix}$$

в том порядке, в котором это произведение определено. Что будет, если попытаться посчитать произведение в другом порядке?

**Решение**   

In [10]:
import numpy as np
A = np.array([i for i in range(1,9)])
A = A.reshape(2,4)
B = np.array([[4, 2, 1],[3, 5, 7],[1, 9, 2],[2, 4, 1]])
C = A @ B
print(C)

[[ 21  55  25]
 [ 61 135  69]]


In [11]:
B @ A

ValueError: shapes (4,3) and (2,4) not aligned: 3 (dim 1) != 2 (dim 0)

### Задача 9 (*)

Дан вектор $v\in \mathbb R^n$ (в виде одномерного `np.array`). Требуется написать программу, строящую матрицу, строками которой являются векторы $t v$ для $t = -1 + k/10,\ k = 0, \ldots, 20$ (то есть $t$ пробегает значения от $-1$ до $1$ с шагом $1/10$, всего $21$ значение). Получающаяся матрица должна иметь $21$ строку и $n$ столбцов. 

**Подсказка.** Для решения задачи вам нужно использовать матричное умножение, а для этого придётся делать из векторов матрицы (вектор-столбцы или вектор-строки). Это можно сделать, например, так:...

In [45]:
def tv(array):
    n = 20
    t = np.diag([-1 + k/10. for k in range(n+1)])
    V = np.array([array for i in range(n+1)])
    return t @ V

In [46]:
my_array = np.array([10, 20, 30, 40])
my_array

array([10, 20, 30, 40])

In [47]:
c = tv(my_array)
c.shape

(21, 4)

In [48]:
c

array([[-10., -20., -30., -40.],
       [ -9., -18., -27., -36.],
       [ -8., -16., -24., -32.],
       [ -7., -14., -21., -28.],
       [ -6., -12., -18., -24.],
       [ -5., -10., -15., -20.],
       [ -4.,  -8., -12., -16.],
       [ -3.,  -6.,  -9., -12.],
       [ -2.,  -4.,  -6.,  -8.],
       [ -1.,  -2.,  -3.,  -4.],
       [  0.,   0.,   0.,   0.],
       [  1.,   2.,   3.,   4.],
       [  2.,   4.,   6.,   8.],
       [  3.,   6.,   9.,  12.],
       [  4.,   8.,  12.,  16.],
       [  5.,  10.,  15.,  20.],
       [  6.,  12.,  18.,  24.],
       [  7.,  14.,  21.,  28.],
       [  8.,  16.,  24.,  32.],
       [  9.,  18.,  27.,  36.],
       [ 10.,  20.,  30.,  40.]])

### Задача 10 (**)
*Рангом* матрицы называется максимальное число её линейно независимых строк или максимальное число её линейно независимых столбцов (можно доказать, что оба числа обязательно совпадают).

Матрицы с малым рангом важны в задачах машинного обучения.

Пусть известно, что прямоугольная матрица $A$ имеет ранг $k$. Доказать, что можно выбрать $k$ строк и $k$ столбцов этой матрицы, таких, что по ним она однозначно восстанавливается. Найти явную формулу для такого восстановления. (Для решения этой задачи вам понадобится понятие обратной матрицы.)